# Generated by Django 3.1.6 on 2021-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_salary',
            options={'verbose_name': 'Employee Salary', 'verbose_name_plural': 'Employees Salaries'},
        ),
    ]
