# Generated by Django 3.1.6 on 2021-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical_detail',
            options={'verbose_name': 'Medical Detail', 'verbose_name_plural': 'Medical Details'},
        ),
    ]
