# Generated by Django 3.1.6 on 2021-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_bank',
            options={'verbose_name': 'Company Bank', 'verbose_name_plural': 'Companies Bank'},
        ),
    ]
