# Generated by Django 3.1.6 on 2021-02-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210214_0000'),
        ('company_bank', '0002_auto_20210212_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_bank',
            new_name='CompanyBank',
        ),
    ]
