# Generated by Django 3.1.6 on 2021-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'verbose_name': 'Invoice Detail', 'verbose_name_plural': 'Invoices Details'},
        ),
    ]
