# Generated by Django 3.1.6 on 2021-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('medicine_detail', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
