# Generated by Django 3.1.6 on 2021-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('License_number', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=400)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
