# Generated by Django 3.1.6 on 2021-02-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210212_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='License_number',
            new_name='license_number',
        ),
    ]
