# Generated by Django 3.1.6 on 2021-02-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('medical_type', models.CharField(max_length=255)),
                ('buy_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sell_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('taxes', models.DecimalField(decimal_places=3, max_digits=8)),
                ('batch_number', models.DecimalField(decimal_places=3, max_digits=8)),
                ('shelf', models.DecimalField(decimal_places=3, max_digits=8)),
                ('expire_date', models.DateField()),
                ('manufacture_date', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('in_stock_total', models.IntegerField()),
                ('quantity_in_strip', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
