# Generated by Django 3.1.6 on 2021-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'verbose_name': 'Company Account', 'verbose_name_plural': 'Companies Accounts'},
        ),
    ]
