# Generated by Django 3.1.6 on 2021-03-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0002_auto_20210212_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'verbose_name': 'Company Account', 'verbose_name_plural': 'Company Accounts'},
        ),
    ]
